services:
    clasyc.generator:
        class: Clasyc\Bundle\SwaggerGeneratorBundle\Services\Generator
        arguments: ['', '@kernel', '@clasyc.finder']
    clasyc.finder:
        class: Clasyc\Bundle\SwaggerGeneratorBundle\Services\DirectoryFinder
        arguments: []